backend:
  name: github
  repo: mezerotm/portfolio

media_folder: "static/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "netlify/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "projects"
    label: "Projects"
    folder: "netlify/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short Description", name: "short_description", widget: "string"}
      - {label: "Long Description", name: "long_description", widget: "markdown"}
      - {label: "Repository", name: "repository", widget: "string"}
      - {label: "Technology Stacks", name: "technology_stacks", widget: "list"}
      - {label: "Technology Fields", name: "technology_fields", widget: "list"}